/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repeated;

import java.util.HashSet;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(duplicateWord("hello abd d  abd"));


    }

    public static String duplicateWord(String string) throws Exception {

        if (string != null) {

            String input = string.toLowerCase();

            String[] strArray = input.replace(",", "").split(" ");

            HashSet<String> repeatedWords = new HashSet<>();
            for (String str : strArray) {
                System.out.println(repeatedWords);
                if (!repeatedWords.add(str))
                return str;
            }

        }
        throw new Exception("there is no repeated word");

    }
}
