/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repeated;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(duplicateWord(" helo how hello you maxn mazsn mana man man"));

    }

    public static String duplicateWord(String string) throws Exception {

        if (string != null) {
            String input = string.toLowerCase();
            ArrayList<String> arrayString=new ArrayList<>();
            String[] strArray = input.replace(",", "").split(" ");
            System.out.println(Arrays.toString(strArray));
            for (int i=0;i<strArray.length;i++){
                    if (arrayString.contains(strArray[i]))
                        return strArray[i];
                else
                        arrayString.add(strArray[i]);

            }

        }
        return "there is no repeated word";
    }
}
