/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package breadthFirst;

public class App {
    public String getGreeting() {
        return "Hello World!";

    }

    public static void main(String[] args) {
      BreadthFirst graph=new BreadthFirst();
        graph.addVertix(1);
        graph.addVertix(2);
        graph.addVertix(3);
        graph.addVertix(4);
        graph.addVertix(5);

        graph.addEdge(0,1);
        graph.addEdge(1,2);
        graph.addEdge(0,3);
        graph.addEdge(3,4);
        graph.addEdge(4,5);
        graph.addEdge(1,4);
        graph.breadthFirst();
    }



}
