/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedListt;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void search() {
        SlinkedList s=new SlinkedList();
        s.insert(5);
        s.insert(10);
        s.insert(15);
        boolean output =s.includes(15);
        assertEquals(true,output);
    }
    @Test public void testString() {
        SlinkedList s=new SlinkedList();
        s.insert(5);
        s.insert(10);
        s.insert(15);
        String output=s.toString();
        assertEquals("{5}->{10}->{15}->Null", output);

    }

    @Test public void searchHead() {
        SlinkedList s=new SlinkedList();
        s.insert(0);

        boolean output =s.includes(0);
        assertEquals(true,output);
    }
}
