/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;
import java.util.*;


public class App {

    public static void main(String[] args) {
    int array[]={1,8,9,4,2,7};
//        System.out.println(.toString());
        Mergesort(array);
}
    public static int[] Mergesort(int[] array){
        int n =array.length;
        if(n>1){
            int mid=n/2;
            int[] left=new int[mid];
            int[] right=new int[n-mid];

            for(int i=0;i<mid;i++){
                left[i]=array[i];
            }
//            for(int j=mid;j<n;j++){
//                right[j]=array[j];
//            }

            System.out.println(Arrays.toString(left));
            Mergesort(left);
            Mergesort(right);

            merge(left,right,array);
        }

        return array;
    }

    public static void merge(int[] left, int[] right, int[] arr){
        int i=0,j=0,k=0;

        while(i<left.length&&j<right.length){
            if(left[i] <= right[j]){
                arr[k] = left[i];
                i = i + 1;
            }else{
                arr[k] = right[j];
                j = j + 1;
            }
            k = k + 1;
            System.out.println(Arrays.toString(arr));

        }


                 if (i == left.length){
            //    set remaining entries in arr to remaining values in right
                 }else{
            //    set remaining entries in arr to remaining values in left
                 }


    };



}