/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;
import java.util.*;


public class App {

    public static void main(String[] args) {

        int[] arr= {45,12,9,20,1,98};
            System.out.println(Arrays.toString(mergesort(arr)));
            }




    public static int[] mergesort(int[] array){
        int n =array.length;
        if(n>1){
            int mid=n/2;
            int[] left=new int[mid];
            int[] right=new int[n-mid];

           for(int i = 0; i < left.length; i++) {
                left[i] = array[i];
            }
            for(int j = 0; j < right.length; j++) {
                right[j] = array[j + mid];
            }

//            System.out.println(Arrays.toString(left));
            mergesort(left);
            mergesort(right);

            merge(left,right,array);
        }

        return array;
    }

    public static void merge(int[] left, int[] right, int[] arr){
        int i=0,j=0,k=0;

        while(i<left.length&&j<right.length){
            if(left[i] <= right[j]){
                arr[k] = left[i];
                i = i + 1;
            }else{
                arr[k] = right[j];
                j = j + 1;
            }
            k = k + 1;
        }

             if(i == left.length) {
            for(int l = j; l < right.length; l++) {
                arr[k] = right[l];
            }
        } else {
            for(int m = i; m < left.length; m++) {
                arr[k] = left[m];
            }
        }


    };



}