/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utilities;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void enQueueTest() {
        AnimalShelter animal=new AnimalShelter();
        animal.enQueue(animal);
        animal.enQueue(animal);
        animal.enQueue(animal);
        assertEquals("dogs",animal.peek());
        animal.deQueue();
        assertEquals("cats",animal.peek());


    }

    @Test
    public void deQueueTest() {
        AnimalShelter animal=new AnimalShelter();
        animal.enQueue(animal);
        animal.enQueue(animal);
        animal.enQueue(animal);
        animal.deQueue();
        animal.deQueue();
        animal.deQueue();
        assertTrue("true",animal.isEmbty());

    }
    @Test
    public void multiBracketValidationTest(){
        MultiBracketValidation bracket=new MultiBracketValidation();
        assertTrue("true",bracket.multiBracket("{hello}"));
        assertTrue("true",bracket.multiBracket("{hello}[there](test)"));
        assertTrue("true",bracket.multiBracket("[({hello})]"));
        assertFalse("false",bracket.multiBracket("]"));
        assertFalse("false",bracket.multiBracket("{]}"));
        assertFalse("false",bracket.multiBracket("{()]"));
        assertFalse("false",bracket.multiBracket("{{{}{}}"));
    }


}
