/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
        TreeIntersection treeOne=new TreeIntersection();
        Node nodeOne=new Node(10);
        Node nodeTow=new Node(15);
        treeOne.addNode(nodeOne,6);
        treeOne.addNode(nodeOne,15);
        treeOne.addNode(nodeOne,8);
        treeOne.addNode(nodeOne,7);
        treeOne.addNode(nodeOne,4);
        treeOne.addNode(nodeOne,2);

        treeOne.addNode(nodeTow,6);
        treeOne.addNode(nodeTow,5);
        treeOne.addNode(nodeTow,56);
        treeOne.addNode(nodeTow,9);
        treeOne.addNode(nodeTow,8);
        treeOne.addNode(nodeTow,15);
        treeOne.addNode(nodeTow,2);
        treeOne.addNode(nodeTow,1);
        treeOne.addNode(nodeTow,30);
        System.out.println(treeOne.treeIntersection(nodeOne,nodeTow));


    }
}
