/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
        TreeIntersection treeOne=new TreeIntersection();
        TreeIntersection.Node root1 = null;
        root1 = treeOne.insert(root1, 5);
        root1 = treeOne.insert(root1, 1);
        root1 = treeOne.insert(root1, 10);
        root1 = treeOne.insert(root1, 0);
        root1 = treeOne.insert(root1, 4);
        root1 = treeOne.insert(root1, 7);
        root1 = treeOne.insert(root1, 9);

        // Create second tree as shown in example
        TreeIntersection.Node root2 = null;
        root2 = treeOne.insert(root2, 10);
        root2 = treeOne.insert(root2, 7);
        root2 = treeOne.insert(root2, 20);
        root2 = treeOne.insert(root2, 4);
        root2 = treeOne.insert(root2, 9);

        treeOne.inorder(root1);
        treeOne.inorder(root2);

        System.out.println(treeOne.printCommon(root1, root2));

    }
}
