/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.util.EmptyStackException;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void pushStack() {
        Stack stack=new Stack();
        assertTrue("true",stack.isEmpty());
        stack.push(5);
        assertFalse("false",stack.isEmpty());
    }
    @Test public void pushStackMulti() {
        Stack stack=new Stack();
        assertTrue("true",stack.isEmpty());
        stack.push(5);
        stack.push(6);
        stack.push(7);
        assertFalse("false",stack.isEmpty());

    }
    @Test public void popStack() {
        Stack stack=new Stack();
        stack.push(5);
        stack.push(6);
        stack.push(7);
        assertEquals(7, stack.peek());
        stack.pop();
        assertEquals(6, stack.peek());


    }
    @Test public void popStackMultiy() {
        Stack stack=new Stack();
        stack.push(5);
        stack.push(6);
        stack.push(7);
        stack.pop();
        stack.pop();
        stack.pop();
        assertTrue("true",stack.isEmpty());
    }
    @Test public void peekStack() {
        Stack stack=new Stack();
        stack.push(5);
        stack.push(6);
        stack.push(7);
        assertEquals(7, stack.peek());
    }

    @Test public void instance() {
        Stack stack=new Stack();
        assertTrue("false", stack.isEmpty());
    }

    @Test(expected = EmptyStackException.class)
    public void stackException() {
        Stack stack=new Stack();
        stack.push(5);
        stack.push(6);
        stack.push(7);
        stack.pop();
        stack.pop();
        stack.pop();
        assertEquals(EmptyStackException.class,stack.peek());



    }
    @Test public void enQueueTest() {
        Queue queue=new Queue();
        assertTrue("true",queue.isEmbty());
        queue.enQueue(5);
        assertFalse("false",queue.isEmbty());
    }
    @Test public void enQueueMulti() {
        Queue queue=new Queue();
        assertTrue("true",queue.isEmbty());
        queue.enQueue(5);
        queue.enQueue(5);
        queue.enQueue(5);
        assertFalse("false",queue.isEmbty());

    }
    @Test public void deQueue() {
        Queue queue=new Queue();
        queue.enQueue(5);
        queue.enQueue(6);
        queue.enQueue(7);
        assertEquals(5, queue.peek());
        queue.deQueue();
        assertEquals(6, queue.peek());


    }
    @Test public void peekQueue() {
        Queue queue=new Queue();
        queue.enQueue(5);
        queue.enQueue(6);
        queue.enQueue(7);
        assertEquals(5, queue.peek());
    }
    @Test public void deQueueMulti() {
        Queue queue=new Queue();
        queue.enQueue(5);
        queue.enQueue(6);
        queue.enQueue(7);
        assertEquals(5, queue.peek());
        queue.deQueue();
        queue.deQueue();
        queue.deQueue();
        assertTrue("true",queue.isEmbty());


    }
    @Test(expected = EmptyStackException.class)
    public void QueueException() {
        Queue queue=new Queue();
        queue.enQueue(5);
        queue.enQueue(6);
        queue.enQueue(7);
        queue.deQueue();
        queue.deQueue();
        queue.deQueue();
        assertEquals(EmptyStackException.class,queue.peek());



    }
    @Test public void instanceQuee() {
        Queue queue=new Queue();
        assertTrue("false", queue.isEmbty());
    }

}
