/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package getEdges;

public class App {
    public String getGreeting() {
        return "Hello World!";

    }

    public static void main(String[] args) {
        AddEdge edge=new AddEdge();
        Node Pandora=new Node("Pandora");
        Node Metroville=new Node("Metroville");
        Node Arendelle=new Node("Arendelle");
        Node Naboo=new Node("Naboo");
        Node Narnia=new Node("Narnia");
        Node NewMonstropolis=new Node("New Monstropolis");

        edge.addNode(Pandora);
        edge.addNode(Arendelle);
        edge.addNode(Metroville);
        edge.addNode(Naboo);
        edge.addNode(NewMonstropolis);
        edge.addNode(Narnia);


        edge.addEdge(Pandora,Metroville,150);
        edge.addEdge(Metroville,Naboo,160);
        edge.addEdge(Narnia,NewMonstropolis,170);
        edge.addEdge(Arendelle,Naboo,180);
        edge.addEdge(Naboo,Narnia,190);

        Node [] array={Pandora,Metroville};
        System.out.println(edge.edgeContain(array));
    }



}
