/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utilities.FizzBuzzTree;

import utilities.FizzBuzzTree.FizzBuzzTree;
import utilities.FizzBuzzTree.Node;
import utilities.FizzBuzzTree.Tree;

import java.util.List;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        Tree tr = new Tree();
        FizzBuzzTree fizzBuzzTree=new FizzBuzzTree();
        tr.root=new utilities.FizzBuzzTree.Node(5);
        tr.root.left=new utilities.FizzBuzzTree.Node(15);
        tr.root.right=new utilities.FizzBuzzTree.Node(4);
        tr.root.left.left=new Node(9);

        fizzBuzzTree.fizzBuzz( tr,tr.root);

        System.out.println("++++++++++++++++++++++++++");
    }
}
