/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedListt;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

//        System.out.println(towList.printLnkedList());
        SlinkedList nodeOne =new SlinkedList();
        SlinkedList nodeTow =new SlinkedList();
        SlinkedList nod =new SlinkedList();
        nodeOne.append(1);
        nodeOne.append(2);
        nodeOne.append(3);
        nodeOne.append(4);
//        nodeOne.revTow();
        System.out.println(nodeOne.printLnkedList());

    }
}
