/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chaleng;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        int[] array={9,5,20,4,8,20,9};
        System.out.println(Arrays.toString(classUnderTest.InsertionSort(array)));
        assertEquals("[4, 5, 8, 9, 9, 20, 20]", Arrays.toString(classUnderTest.InsertionSort(array)));

    }

    @Test public void testTow() {
        App classUnderTest = new App();
        int[] array={100,500,350,1000,987};
        System.out.println(Arrays.toString(classUnderTest.InsertionSort(array)));
        assertEquals("[100, 350, 500, 987, 1000]", Arrays.toString(classUnderTest.InsertionSort(array)));

    }

    @Test public void oneValue() {
        App classUnderTest = new App();
        int[] array={100};
        System.out.println(Arrays.toString(classUnderTest.InsertionSort(array)));
        assertEquals("[100]", Arrays.toString(classUnderTest.InsertionSort(array)));

    }

}
