/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

public class Library {
    public static void main(String[] args) {
        Stack stack=new Stack();
        Queue queue=new Queue();
        queue.enQueue(5);
        queue.enQueue(6);
        queue.enQueue(7);

        stack.push(5 );
        stack.push(6);
        stack.push(68);
        stack.pop();

        System.out.println(stack.toString());

    }}
