/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utilities;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        AnimalShelter classUnderTest = new AnimalShelter();
        Cat cat = new Cat("Mew","anything",5);
        Cat cat1 = new Cat("anything","anything",4);
        Dogs dog = new Dogs("anything","anything",3);
        classUnderTest.enQueue(cat);
        classUnderTest.enQueue(dog);
        classUnderTest.enQueue(cat1);
        System.out.println(classUnderTest.dogy.peek());
    }
}
