/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utilities;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        AnimalShelter animalShelter=new AnimalShelter();

    }
}
