/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DepthFirst;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        DepthFirst g = new DepthFirst(5);
        g.addEdge(0,1);
//        g.addEdge(3,2);
//        g.addEdge(2,4);
//        g.addEdge(1,4);
//        g.addEdge(3,1);
//        g.addEdge(2,0);
    }
}
