/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public String getGreeting() {
        return "Hello World!";

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int[] array={1,0,2,2,1,0,0,2,1,2};
        sortArray(array);
    }

    public static void sortArray(int[] arr){
        int num=0;
        for(int i=0;i<arr.length;i++){
            for(int j=1;j<arr.length-1;i++){
                if(arr[i]>arr[j]){
                    num=arr[i];
                    arr[i]=arr[j];
                    arr[j]=num;
                }
            }
        }
        for(int i=0;i<arr.length;i++){
            System.out.println(arr[i]);

        }
    }
}
