/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

public class App {
    public static void main(String[] args) {

        int arr[] = {10, 7, 8, 9, 1, 5};
        int n = arr.length;

        sort(arr, 0, n-1);

        System.out.println("sorted array");
        printArray(arr);
    }




    public static int partition(int arr[], int left, int right)
    {
        int pivot = arr[right];
        int low = (left-1);
        for (int j=left; j<right; j++)
        {
            if (arr[j] <= pivot)
            {
                low++;

                //swap
                int temp = arr[low];
                arr[low] = arr[j];
                arr[j] = temp;
            }
        }

        int temp = arr[low+1];
        arr[low+1] = arr[right];
        arr[right] = temp;

        return low+1;
    }



    public static int[] sort(int arr[], int left, int right)
    {
        if (left < right)
        {
            int position = partition(arr, left, right);

            sort(arr, left, position-1);
            sort(arr, position+1, right);
        }

        return arr;
    }

    public static void printArray(int arr[])
    {
        int n = arr.length;
        for (int i=0; i<n; ++i)
            System.out.print(arr[i]+" ");
        System.out.println();
    }
}
