/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {


//    __________________________________________{{{{code Chaleng 16}}}}

    @Test public void findMaxTest() {
        Node root=new Node();

        BinarySearchTree tree = new BinarySearchTree(root);
        BinaryTree treeTow = new BinaryTree();
        tree.addThre(9,root);
        tree.addThre(10,root);
        tree.addThre(5,root);
        assertEquals(10, treeTow.findMax(root));
    }
    @Test public void findMaxTestTow() {
        Node root=new Node();

        BinarySearchTree tree = new BinarySearchTree(root);
        BinaryTree treeTow = new BinaryTree();

        tree.addThre(9,root);
        assertEquals(9, treeTow.findMax(root));
    }

    @Test public void findMaxTestThree() {
        Node root=new Node();

        BinarySearchTree tree = new BinarySearchTree(root);
        BinaryTree treeTow = new BinaryTree();

        assertEquals(0, treeTow.findMax(root));
    }

    @Test public void findMaxTestt() {
        Node root=new Node();

        BinarySearchTree tree = new BinarySearchTree(root);
        BinaryTree treeTow = new BinaryTree();
        tree.addThre(9,root);
        tree.addThre(10,root);
        tree.addThre(5,root);
        tree.addThre(90,root);
        tree.addThre(78,root);
        tree.addThre(69,root);
        tree.addThre(24,root);
        assertEquals(90, treeTow.findMax(root));
    }
//    __________________________________________{{{{code Chaleng 16}}}}

}
